[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10

[program:gunicorn]
command=gunicorn --bind 0.0.0.0:8000 pers_project.wsgi:application --workers=4 --timeout=120
directory=/app
user=appuser
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/gunicorn.log
stderr_logfile=/var/log/supervisor/gunicorn-error.log
environment=DJANGO_SETTINGS_MODULE="pers_project.settings"

[program:celery]
command=celery -A pers_project worker -l info --concurrency=4
directory=/app
user=appuser
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/celery.log
stderr_logfile=/var/log/supervisor/celery-error.log
environment=DJANGO_SETTINGS_MODULE="pers_project.settings"

[program:celery-beat]
command=celery -A pers_project beat -l info
directory=/app
user=appuser
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/celery-beat.log
stderr_logfile=/var/log/supervisor/celery-beat-error.log
environment=DJANGO_SETTINGS_MODULE="pers_project.settings"